### ISSUE TITLE
Cannot read property 'transformedQuery' of undefined

### ISSUE THREAD

**Issue by dchambers** [apollostack/GitHunt-API#139]
I get this error when starting the server:

```
dchamb:GitHunt-API dchamb$ yarn start
yarn start v0.18.0
$ nodemon api/index.js --watch api --exec babel-node 
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/dchamb/dev/GitHunt-API/api/**/*
[nodemon] starting `babel-node api/index.js`
API Server is now running on http://localhost:3010
Websocket Server is now running on http://localhost:8080
TypeError: Cannot read property 'transformedQuery' of undefined
    at /Users/dchamb/dev/GitHunt-API/node_modules/extractgql/src/server/serverUtil.ts:91:52
    at Layer.handle [as handle_request] (/Users/dchamb/dev/GitHunt-API/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/dchamb/dev/GitHunt-API/node_modules/express/lib/router/index.js:312:13)
    at /Users/dchamb/dev/GitHunt-API/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/dchamb/dev/GitHunt-API/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/dchamb/dev/GitHunt-API/node_modules/express/lib/router/index.js:271:10)
    at /Users/dchamb/dev/GitHunt-API/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/dchamb/dev/GitHunt-API/node_modules/raw-body/index.js:262:16)
    at done (/Users/dchamb/dev/GitHunt-API/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/Users/dchamb/dev/GitHunt-API/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I tried installing the dependencies with both npm & yarn in case the `yarn.lock` file was or wasn't relevant.

**Comment by JimLiu** [comment]
same issue

**Comment by dchambers** [comment]
That did the trick @JimLiu, much appreciated 👍

**Comment by Poincare** [comment]
Ah, I think this is a extracted queries issue. Have you tried to copy the `extracted_queries.json` from Githunt-React into your GitHunt-API directory? Are you both using React?

We should have some documentation around this soon.

**Comment by JimLiu** [comment]
@Poincare 
Yes, I tried to  copy the `extracted_queries.json` file from `Githunt-React` into my `GitHunt-API` directory
then I opened http://localhost:3010/graphiql, but I still got that error.

**Comment by Poincare** [comment]
Ah. Graphiql will not work with persisted queries. Is the primary application (i.e. the GitHunt UI) working for you correctly?

**Comment by JimLiu** [comment]
@Poincare 
`GitHunt-React` did not work.

```
[nodemon] starting `node server_bundle.js index.js`
module.js:472
    throw err;
    ^

Error: Cannot find module '/sources/GitHunt-React/server_bundle.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

I couldn't find the server_bundle.js, so I had to give up!

**Comment by Poincare** [comment]
That was fixed just yesterday [right here](https://github.com/apollostack/GitHunt-React/commit/b6c61295688e74a25c7f2b85d51a6f1069dcacd2). Could you pull from the GitHunt-React repository and give it a try again?

**Comment by JimLiu** [comment]
@Poincare 
Cool, it works now!

Thanks for your great work!

**Comment by Poincare** [comment]
Great! I will go ahead and close this issue.
